FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["test.slnx", "./"]
COPY ["src/OpenSource1.Core/OpenSource1.Core.csproj", "src/OpenSource1.Core/"]
COPY ["src/OpenSource1.Application/OpenSource1.Application.csproj", "src/OpenSource1.Application/"]
COPY ["src/OpenSource1.Infrastructure/OpenSource1.Infrastructure.csproj", "src/OpenSource1.Infrastructure/"]
COPY ["src/OpenSource1.Mvc/OpenSource1.Mvc.csproj", "src/OpenSource1.Mvc/"]
RUN dotnet restore "src/OpenSource1.Mvc/OpenSource1.Mvc.csproj"
COPY . .
RUN dotnet publish "src/OpenSource1.Mvc/OpenSource1.Mvc.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM runtime AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "OpenSource1.Mvc.dll"]
