// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenSource1.Infrastructure.Data;

#nullable disable

namespace OpenSource1.Infrastructure.Data.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260925170621_ReemplazarStockPorLibro")]
    partial class ReemplazarStockPorLibro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenSource1.Core.Entities.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("boolean");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DireccionLinea1")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DireccionLinea2")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("EsPredeterminado")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PaisCodigo")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Almacenes_CreatedAtUtc");

                    b.HasIndex("EsPredeterminado")
                        .IsUnique()
                        .HasDatabaseName("IX_Almacenes_EsPredeterminado")
                        .HasFilter("\"EsPredeterminado\" = true AND \"IsDeleted\" = false");

                    b.ToTable("Almacenes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            Bloqueado = false,
                            Codigo = "PRINCIPAL",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            EsPredeterminado = true,
                            IsDeleted = false,
                            Nombre = "Almacén principal"
                        });
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_AppSettings_CreatedAtUtc");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.CategoriaProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoriaPadreId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPadreId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_CategoriasProducto_CreatedAtUtc");

                    b.ToTable("CategoriasProducto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000001"),
                            Codigo = "GENERAL",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            Nombre = "General"
                        });
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.Entrada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Entradas_CreatedAtUtc");

                    b.ToTable("Entradas", (string)null);
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.Inventario.AplicacionMovimientoProducto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<long>("MovimientoEntradaId")
                        .HasColumnType("bigint");

                    b.Property<long>("MovimientoSalidaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MovimientoEntradaId")
                        .HasDatabaseName("IX_AplicacionesMovimientoProducto_MovimientoEntradaId");

                    b.HasIndex("MovimientoSalidaId")
                        .HasDatabaseName("IX_AplicacionesMovimientoProducto_MovimientoSalidaId");

                    b.ToTable("AplicacionesMovimientoProducto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Aplicaciones_Cantidad_Positiva", "\"Cantidad\" > 0");
                        });
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.Inventario.MovimientoProducto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("CantidadFacturada")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("CantidadPorUnidadMedida")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("CantidadRestante")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("ClaveOrigen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("FechaDocumento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("NumeroLineaDocumento")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SocioNegocioId")
                        .HasColumnType("uuid");

                    b.Property<short>("TipoDocumento")
                        .HasColumnType("smallint");

                    b.Property<short>("TipoMovimiento")
                        .HasColumnType("smallint");

                    b.Property<short>("TipoOrigen")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UnidadMedidaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId")
                        .HasDatabaseName("IX_MovimientosProducto_AlmacenId");

                    b.HasIndex("SocioNegocioId");

                    b.HasIndex("UnidadMedidaId");

                    b.HasIndex("ProductoId", "AlmacenId", "FechaRegistro", "Id")
                        .HasDatabaseName("IX_MovimientosProducto_Fifo")
                        .HasFilter("\"CantidadRestante\" > 0");

                    b.ToTable("MovimientosProducto", null, t =>
                        {
                            t.HasCheckConstraint("CK_MovimientosProducto_Cantidad_NoCero", "\"Cantidad\" <> 0");

                            t.HasCheckConstraint("CK_MovimientosProducto_Factor_Positivo", "\"CantidadPorUnidadMedida\" > 0");

                            t.HasCheckConstraint("CK_MovimientosProducto_Restante", "\"CantidadRestante\" IS NULL OR (\"CantidadRestante\" >= 0 AND \"CantidadRestante\" <= \"Cantidad\")");
                        });
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.Inventario.MovimientoValor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ajuste")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadFacturada")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("CantidadValorada")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("ClaveOrigen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("CostoPorUnidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<Guid?>("GrupoInventarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GrupoNegocioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GrupoProductoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ImporteCosto")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ImporteCostoPosteadoContabilidad")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ImporteVenta")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long?>("MovimientoProductoId")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("NumeroLineaDocumento")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<short>("TipoDocumento")
                        .HasColumnType("smallint");

                    b.Property<short>("TipoMovimiento")
                        .HasColumnType("smallint");

                    b.Property<short>("TipoOrigen")
                        .HasColumnType("smallint");

                    b.Property<short>("TipoValor")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("MovimientoProductoId");

                    b.HasIndex("ProductoId", "AlmacenId", "FechaRegistro")
                        .HasDatabaseName("IX_MovimientosValor_PendientePosteoContabilidad")
                        .HasFilter("\"ImporteCosto\" <> \"ImporteCostoPosteadoContabilidad\"");

                    b.ToTable("MovimientosValor", (string)null);
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.LineaSerie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("FechaInicial")
                        .HasColumnType("date");

                    b.Property<int>("Incremento")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NumeroFinal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroInicial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SerieId")
                        .HasColumnType("uuid");

                    b.Property<string>("UltimoNumeroUsado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_LineasSerie_CreatedAtUtc");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("IX_LineasSerie_SerieId");

                    b.ToTable("LineasSerie", (string)null);
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Bloqueado")
                        .HasColumnType("smallint");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("CostoAjustado")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CostoEstandar")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<short>("MetodoCosteo")
                        .HasColumnType("smallint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("UnidadMedidaBaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Productos_CreatedAtUtc");

                    b.HasIndex("UnidadMedidaBaseId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.Serie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("PermiteHuecos")
                        .HasColumnType("boolean");

                    b.Property<bool>("PorDefecto")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Series_CreatedAtUtc");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.SocioNegocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Bloqueado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("LimiteCredito")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroDocumentoFiscal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TerminoPagoId")
                        .HasColumnType("uuid");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint");

                    b.Property<short>("TipoDocumentoFiscal")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Direccion", "OpenSource1.Core.Entities.SocioNegocio.Direccion#DireccionFiscal", b1 =>
                        {
                            b1.Property<string>("Linea1")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("DireccionLinea1");

                            b1.Property<string>("Linea2")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("DireccionLinea2");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Pais", "OpenSource1.Core.Entities.SocioNegocio.Pais#Pais", b1 =>
                        {
                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("PaisCodigo");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PaisNombre");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Sector", "OpenSource1.Core.Entities.SocioNegocio.Sector#Sector", b1 =>
                        {
                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Sector");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_SociosNegocio_CreatedAtUtc");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_SociosNegocio_Email");

                    b.HasIndex("NumeroDocumentoFiscal")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false AND \"NumeroDocumentoFiscal\" IS NOT NULL");

                    b.HasIndex("TerminoPagoId");

                    b.ToTable("SociosNegocio", (string)null);
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.TerminoPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DiasDescuento")
                        .HasColumnType("integer");

                    b.Property<int>("DiasVencimiento")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasPrecision(9, 5)
                        .HasColumnType("numeric(9,5)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_TerminosPago_CreatedAtUtc");

                    b.ToTable("TerminosPago", (string)null);
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.UnidadMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("Decimales")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_UnidadesMedida_CreatedAtUtc");

                    b.ToTable("UnidadesMedida", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Codigo = "UND",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Decimales = (short)0,
                            IsDeleted = false,
                            Nombre = "Unidad"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Codigo = "KG",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Decimales = (short)3,
                            IsDeleted = false,
                            Nombre = "Kilogramo"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Codigo = "GR",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Decimales = (short)0,
                            IsDeleted = false,
                            Nombre = "Gramo"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Codigo = "LT",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Decimales = (short)3,
                            IsDeleted = false,
                            Nombre = "Litro"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            Codigo = "ML",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Decimales = (short)0,
                            IsDeleted = false,
                            Nombre = "Mililitro"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            Codigo = "CJA",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Decimales = (short)0,
                            IsDeleted = false,
                            Nombre = "Caja"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000007"),
                            Codigo = "DOC",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Decimales = (short)0,
                            IsDeleted = false,
                            Nombre = "Docena"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000008"),
                            Codigo = "PAQ",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Decimales = (short)0,
                            IsDeleted = false,
                            Nombre = "Paquete"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000009"),
                            Codigo = "MT",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Decimales = (short)2,
                            IsDeleted = false,
                            Nombre = "Metro"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000010"),
                            Codigo = "LB",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Decimales = (short)3,
                            IsDeleted = false,
                            Nombre = "Libra"
                        });
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.UnidadMedidaProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadPorUnidadMedida")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnidadMedidaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UnidadMedidaId");

                    b.HasIndex("ProductoId", "UnidadMedidaId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("UnidadesMedidaProducto", null, t =>
                        {
                            t.HasCheckConstraint("CK_UnidadMedidaProducto_Cantidad_Positiva", "\"CantidadPorUnidadMedida\" > 0");
                        });
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.CategoriaProducto", b =>
                {
                    b.HasOne("OpenSource1.Core.Entities.CategoriaProducto", null)
                        .WithMany()
                        .HasForeignKey("CategoriaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.Inventario.AplicacionMovimientoProducto", b =>
                {
                    b.HasOne("OpenSource1.Core.Entities.Inventario.MovimientoProducto", null)
                        .WithMany()
                        .HasForeignKey("MovimientoEntradaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenSource1.Core.Entities.Inventario.MovimientoProducto", null)
                        .WithMany()
                        .HasForeignKey("MovimientoSalidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AplicacionesMovimientoProducto_MovimientosProducto_Movimie~1");
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.Inventario.MovimientoProducto", b =>
                {
                    b.HasOne("OpenSource1.Core.Entities.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenSource1.Core.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenSource1.Core.Entities.SocioNegocio", null)
                        .WithMany()
                        .HasForeignKey("SocioNegocioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenSource1.Core.Entities.UnidadMedida", null)
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.Inventario.MovimientoValor", b =>
                {
                    b.HasOne("OpenSource1.Core.Entities.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenSource1.Core.Entities.Inventario.MovimientoProducto", null)
                        .WithMany()
                        .HasForeignKey("MovimientoProductoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenSource1.Core.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.LineaSerie", b =>
                {
                    b.HasOne("OpenSource1.Core.Entities.Serie", null)
                        .WithMany()
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.Producto", b =>
                {
                    b.HasOne("OpenSource1.Core.Entities.CategoriaProducto", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenSource1.Core.Entities.UnidadMedida", null)
                        .WithMany()
                        .HasForeignKey("UnidadMedidaBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.SocioNegocio", b =>
                {
                    b.HasOne("OpenSource1.Core.Entities.TerminoPago", null)
                        .WithMany()
                        .HasForeignKey("TerminoPagoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OpenSource1.Core.Entities.UnidadMedidaProducto", b =>
                {
                    b.HasOne("OpenSource1.Core.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenSource1.Core.Entities.UnidadMedida", null)
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
